apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep-postgres
  name: dep-postgres
  namespace: icgroup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep-postgres
    spec:
      containers:
      - image: postgres:10
        name: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: odoo_user
        - name: POSTGRES_PASSWORD
          value: odoo_password
        - name: POSTGRES_DB
          value: postgres
        resources: {}
status: {}