apiVersion: v1
kind: Service
metadata:
  name: nodeport
  labels:
    app: ic-webapp
    env: dev
  namespace: icgroup
spec:
  type: NodePort
  selector:
    app:  ic-webapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088