apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep-odoo
    env: dev
  name: dep-odoo
  namespace: icgroup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep-odoo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep-odoo
    spec:
      containers:
      - image: odoo:13.0
        name: odoo
        securityContext:
          runAsUser: 0
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "chmod -R 777 /etc/odoo"]
        env:
        - name: USER
          value: odoo_user
        - name: PASSWORD
          value: odoo_password
        - name: HOST
          value: postgres
        ports:
        - containerPort: 8069
        volumeMounts:
        - name: persistence-volume
          mountPath: /etc/odoo
        - name: lib-persistence-volume
          mountPath: /var/lib/odoo
        - name: extra-addons-persistence-volume
          mountPath: /mnt/extra-addons
      volumes:
      - name: persistence-volume
        hostPath:
          path: /data_docker/config
      - name: lib-persistence-volume
        persistentVolumeClaim:
          claimName: odoo-pvc
      - name: extra-addons-persistence-volume
        hostPath:
          path: /data_docker/addons           
